#####
# Configuration file for the Edge Device App (EDA)
#
# This provides a section-based configuration format for use by
# ConfigUtil with keys defined in ConfigConst.
#
# IMPORTANT: Edit this file to meet your local system requirements.
#

#
# MQTT client configuration information
#
[Mqtt.GatewayService]
# NOTE: Use the fully qualified path
credFile       = /mnt/d/pdt/pdt-edge-components/cred/PdtMqttLocalCred.props
certFile       = /mnt/d/pdt/pdt-edge-components/cert/PdtMqttLocalCertFile.pem
host           = localhost
port           = 1883
securePort     = 8883
defaultQoS     = 0
keepAlive      = 60
enableAuth     = False
enableCrypt    = False

#
# Data client configuration information (InfluxDB)
#
[Data.GatewayService]
# NOTE: Use the fully qualified path
credFile       = /mnt/d/pdt/pdt-edge-components/cred/PdtInfluxCred.props
host           = localhost
port           = 8086
securePort     = 8886
enableAuth     = True
enableCrypt    = False
cmdDataBucket     = pdt-cmd-data
connDataBucket    = pdt-conn-data
sensorDataBucket  = pdt-sensor-data
sysDataBucket     = pdt-sys-data

#
# EDA specific configuration information
#
[EdgeDevice]
deviceID = edgedevice001
deviceLocationID = edgedevice001
enableMqttClient = True
enableTsdbClient = False
enableLogging    = True
enableMsgQueue   = True
enableSystemPerformance = True
enableActuation = True
enableSensing = True
enableSimEngineUpdates = True
sendEventDisplayUpdates = False
updateDisplayOnActuation = True
useDataGenerationSettings = True
runForever = True

# test specific properties
[Settings.Testing]
# NOTE: Use the fully qualified path
testCdaDataPath  = /tmp/cda-data
testGdaDataPath  = /tmp/gda-data
testEmptyApp     = False

# system performance specific properties
[Settings.SystemPerformance]
enableOperation = True
pollCycleSecs = 5

# environmental sim specific properties
[Settings.Environmental]
enableOperation = True
pollCycleSecs = 5

# only one of the three should be True
enableSimulator = True
enableEmulator = False
enableSenseHAT = False

humiditySimFloor   =   35.0
humiditySimCeiling =   45.0
pressureSimFloor   =  990.0
pressureSimCeiling = 1010.0
tempSimFloor       =   15.0
tempSimCeiling     =   25.0
handleTempChangeOnDevice = True
triggerHvacTempFloor     = 18.0
triggerHvacTempCeiling   = 20.0

# wind turbine specific properties
[Settings.WindTurbine]
pollCycleSecs = 5
enableOperation = True
enablePowerGenerationSim = True
enableCommandName = enableWindTurbine

# factory workcell specific properties
[Settings.FactoryWorkcell]
pollCycleSecs = 5
enableOperation = True

name = TestWorkcellA
typeCategoryID = 12000
enableRoboticManipulator = True
enableHopper = True
enableConveyor = True
enablePalletLoading = True

hopperTypeID = 12001
hopperTypeName = hopper 
conveyorTypeID = 12002
conveyorTypeName = conveyor
roboticManipulatorTypeID = 12003
roboticManipulatorName = roboticManipulator
palletLoaderTypeID = 12004
palletLoaderName = palletLoader
